[project]
name = "tkr-ibmq-worker-impl"
version = "0.2.0"
description = "A Tierkreis worker for compilation of ibmq backends."
authors = [ {name = "Quantinuum Tierkreis Team"} ]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "tierkreis",
    "pytket",
    "pytket-qiskit",
    "tkr-ibmq-worker"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.uv.sources]
tierkreis = { workspace = true }
tkr-ibmq-worker = { workspace = true }

[project.scripts]
tkr-ibmq-worker-impl = "src.main:main"
