# PBS Configuration File

# PBS installation directory
PBS_EXEC=/opt/pbs

# Server hostname
PBS_SERVER=server
PBS_START_SERVER=0
PBS_START_SCHED=0
PBS_START_COMM=0
PBS_START_MOM=0
PBS_EXEC=/opt/pbs
PBS_HOME=/var/spool/pbs
PBS_CORE_LIMIT=unlimited
PBS_SCP=/bin/scp


# Service ports
PBS_DATA_SERVICE_PORT=15007
PBS_MANAGER_SERVICE_PORT=15001
PBS_SCHEDULER_SERVICE_PORT=15004
PBS_MOM_SERVICE_PORT=15002
PBS_MOM_RM_PORT=15003

