#!/usr/bin/env python3
# /// script
# requires-python = ">=3.12"
# ///
"""Compatibility wrapper for PBS Pro-style qstat flags in local OpenPBS.

Generated by GPT-5.5

OpenPBS 22.05 does not support `qstat -x`, while PBS Professional does. The
Rust PBS wrapper uses `qstat -x -f -F json <jobid>` so finished jobs remain
queryable. For the local Docker test cluster, emulate that narrow behavior by
combining live `qstat` JSON with finished-job records from PBS accounting logs.
"""

import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path

REAL_QSTAT = "/opt/pbs/bin/qstat.openpbs"
ACCOUNTING_DIR = (
    Path(os.environ.get("PBS_HOME", "/var/spool/pbs")) / "server_priv" / "accounting"
)


def split_args(args: list[str]) -> tuple[bool, bool, list[str], list[str]]:
    include_history = False
    json_output = False
    passthrough = []
    job_ids = []
    skip_next = False

    for index, arg in enumerate(args):
        if skip_next:
            passthrough.append(arg)
            skip_next = False
            continue
        if arg == "-x":
            include_history = True
            continue
        if arg == "-F" and index + 1 < len(args):
            json_output = args[index + 1] == "json"
            passthrough.append(arg)
            skip_next = True
            continue
        if arg == "-Fjson":
            json_output = True
            passthrough.append(arg)
            continue
        passthrough.append(arg)
        if not arg.startswith("-"):
            job_ids.append(arg.split(".", 1)[0])

    return include_history, json_output, passthrough, job_ids


def run_real_qstat(args: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [REAL_QSTAT, *args],
        check=False,
        capture_output=True,
        text=True,
    )


def accounting_exit_statuses() -> dict[str, int]:
    statuses = {}
    if not ACCOUNTING_DIR.exists():
        return statuses

    for path in sorted(ACCOUNTING_DIR.iterdir()):
        if not path.is_file():
            continue
        with path.open(encoding="utf-8", errors="replace") as handle:
            for line in handle:
                fields = line.rstrip("\n").split(";", 3)
                if len(fields) != 4 or fields[1] != "E":
                    continue
                job_id = fields[2].split(".", 1)[0]
                match = re.search(r"(?:^|\s)Exit_status=([-0-9]+)(?:\s|$)", fields[3])
                if match:
                    statuses[job_id] = int(match.group(1))
    return statuses


def merge_live_jobs(output: str) -> dict[str, object]:
    if not output.strip():
        return {}
    try:
        payload = json.loads(output)
    except json.JSONDecodeError:
        return {}
    jobs = payload.get("Jobs", {})
    if isinstance(jobs, dict):
        return jobs
    return {}


def main() -> int:
    include_history, json_output, passthrough, job_ids = split_args(sys.argv[1:])

    if not include_history or not json_output or not job_ids:
        os.execv(REAL_QSTAT, [REAL_QSTAT, *passthrough])

    live_jobs = {}
    missing_job_ids = []
    job_id_set = set(job_ids)
    for job_id in job_ids:
        query_args = [
            arg for arg in passthrough if arg.split(".", 1)[0] not in job_id_set
        ]
        result = run_real_qstat([*query_args, job_id])
        if result.returncode == 0:
            live_jobs.update(merge_live_jobs(result.stdout))
        else:
            missing_job_ids.append(job_id)

    finished = accounting_exit_statuses()
    for job_id in missing_job_ids:
        if job_id in finished:
            live_jobs[job_id] = {
                "job_state": "F",
                "Exit_status": finished[job_id],
            }

    print(
        json.dumps(
            {
                "timestamp": int(time.time()),
                "pbs_version": "openpbs-local",
                "pbs_server": os.environ.get("PBS_SERVER", "pbs-server"),
                "Jobs": live_jobs,
            }
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
