#!/bin/bash
SCRIPT_FILE=$(basename "$1")

# This emulates the sbatch command assuming .tkr is in $HOME
# Rewrites all occurrences of $HOME in the script to /root,
# which is where the home directory is mounted in the container
docker cp "$1" pbs-server:/data/"$SCRIPT_FILE"
docker exec -u root pbs-server chown pbsuser:pbsuser /data/"$SCRIPT_FILE"
docker exec -u pbsuser pbs-server sh -c 'sed -i "s|$2|/home/pbsuser|g" /data/$1 && \
qsub /data/$1' sh "$SCRIPT_FILE" "$HOME"
