"""String template for the project initialization."""


def python_worker_impl(worker_name: str) -> str:
    """Generate a python worker impl.py.

    :param worker_name: The name of the worker.
    :type worker_name: str
    :return: The generated worker_impl.py content.
    :rtype: str
    """
    worker_name = worker_name.replace("-", "_")
    return f"""#TODO Implement your custom worker here.
from tierkreis import Worker
from tierkreis.exceptions import TierkreisError

worker = Worker("{worker_name}")

@worker.task()
def your_worker_task(value: int) -> int:
    return value

"""


def python_worker_main(worker_name: str) -> str:
    """Generate a python worker main.py.

    :param worker_name: Name of the worker.
    :type worker_name: str
    :return: The generated main.py content.
    :rtype: str
    """
    return f"""#AUTOGENERATED, DO NOT MODIFY!    
from sys import argv

from tkr_{worker_name.replace("-", "_")}_impl import worker

def main():
    worker.app(argv)


if __name__ == "__main__":
    main()

"""


def python_worker_pyproject(worker_name: str) -> str:
    """Generate the pyproject.toml for the worker workspace.

    This is the full project containing the implementation.

    :param worker_name: Name of the worker.
    :type worker_name: str
    :return: The generated pyproject.toml content.
    :rtype: str
    """
    worker_name = worker_name.replace("_", "-")
    template = f"""[project]
name = "tkr-{worker_name}-impl"
version = "0.1.0"
description = "A tierkreis worker implementation."
readme = "README.md"
requires-python = ">=3.12"
authors = [ {{name = "Your Name", email = "you@example.com"}} ]
dependencies = [
    "tierkreis",
]

[tool.uv.workspace]
members = [
    "api",
]

[tool.uv.sources]
tkr-{worker_name}= {{ workspace = true }}

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
tkr-{worker_name} = "tkr_{worker_name.replace("-", "_")}_impl.main:main"

"""
    return template


def python_worker_api_pyproject(worker_name: str) -> str:
    """Generate the pyproject.toml for the worker api.

    This is the API subproject containing the worker stubs.

    :param worker_name: Name of the worker.
    :type worker_name: str
    :rtype: str
    """
    package_name = worker_name.replace("_", "-")
    template = f"""[project]
name = "tkr-{package_name}"
version = "0.1.0"
description = "A tierkreis worker api."
readme = "README.md"
requires-python = ">=3.12"
authors = [ {{name = "Your Name", email = "you@example.com"}} ]
dependencies = [
    "tierkreis",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel.force-include]
"api.py" = "{worker_name}.py"

"""
    return template


def external_worker_idl(worker_name: str) -> str:
    """Generate a typespec file for a worker.

    :param worker_name: The name of the worker.
    :type worker_name: str
    :return: The generated typespec content.
    :rtype: str
    """
    return f"""model YourModel {{
        value: int
}}

interface {worker_name} {{
    your_function(value: int): YourModel;
}}

"""


def default_graph(worker_name: str) -> str:
    """Generate a default graph example using a worker.

    :param worker_name: The name of the worker.
    :type worker_name: str
    :return: The generated main graph content.
    :rtype: str
    """
    worker_name = worker_name.replace("-", "_")
    return f"""from typing import NamedTuple
from pathlib import Path
from uuid import UUID

from tierkreis.builder import GraphBuilder
from tierkreis.controller import run_graph
from tierkreis.controller.data.models import TKR, OpaqueType
from tierkreis.executor import ShellExecutor, UvExecutor
from tierkreis.storage import FileStorage, read_outputs

from {worker_name} import your_worker_task

class GraphInputs(NamedTuple):
    value: TKR[int]


class GraphOutputs(NamedTuple):
    value: TKR[int]


def workflow() -> GraphBuilder[GraphInputs, GraphOutputs]:
    g = GraphBuilder(GraphInputs, GraphOutputs)
    out = g.task(your_worker_task(g.inputs.value))
    g.outputs(GraphOutputs(value=out))
    return g

def main() -> None:
    graph = workflow()
    storage = FileStorage(workflow_id=UUID(int=12345), name=your_workflow")
    executor = UvExecutor(
        Path(__file__).parent.parent / "workers", storage.logs_path
    )
    # Use the following executor to run installed workers like tkr-*-worker
    # executor = ShellExecutor(Path(), storage.workflow_dir)
    # To use both look at the following:
    # https://quantinuum.github.io/tierkreis/executors/index.html#combining-executors
    storage.clean_graph_files()
    run_graph(storage, executor, graph.get_data(), {{"value": 1}})
    result = read_outputs(graph, storage)
    print("Value is: ", result)

if __name__ == "__main__":
    main()

"""


def worker_init() -> str:
    """Generate a toplevel init for the worker.

    :return: An init template
    :rtype: str
    """
    return """from from .api.api import *

"""


def worker_impl_init() -> str:
    """Generate a toplevel init for the worker.

    :return: An init template
    :rtype: str
    """
    return """from .impl import worker

__all__ = ["worker"]
"""


def worker_readme(worker_name: str) -> str:
    """Generate a README.md template for a worker.

    :param worker_name: The name of the worker.
    :type worker_name: str
    :return: The generated README.md content.
    :rtype: str
    """
    return f"""# {worker_name} Worker
    
## Introduction

This is the root for a custom worker you just created.
Conceptually, a worker is a wrapper around some functionality you want to use in your graphs.
It can be as simple as a single function or a whole library.
The only requirement is that it has to be wrapped in a way that tierkreis can understand,
e.g. using the Worker class for python workers or an IDL file for external workers.
How to use existing functionality we will cover further down.

Workers act as an independent project, which means they don't need to share dependencies with you graph code.
This worker is automatically included in your top level project as a dependency so you can immediately use it in your graphs.
If you want to decouple it from your graph code, you can either define it as a workspace member
or publish it to a package index and install it as a dependency in your graph project instead of using a path dependency.

## Project structure

The recommend structure for a python worker is as follows:
```
{worker_name}/
├── api/
│    ├── api.py
│    └── pyproject.toml
├── tkr_{worker_name}_impl/
│    ├── lib/ (not generated)
│    ├── __init__.py
│    ├── impl.py
│    └── main.py
├── README.md (this file)
└── pyproject.toml
```
The `tkr_{worker_name}_impl` directory contains the worker tasks in `impl.py` which are used during runtime of a workflow.
For this the toplevel pyproject.toml defines a script entry point which points to the `main.py` file.
You should not edit this `main.py`.
The `lib` directory is a placeholder for your library code.
If you're using a preexisting codebase we recommend move your code base there and point the worker tasks at it.
You than can import the functionality in `worker_impl.py`.
The source code is packaged as `trk-{worker_name}-impl`.


The `api` directory contains the stubs which are used during construction of a graph.
They can be generated using the `trk init stubs` command and are not required to be present during runtime.
They are encapsulated in a separate package `tkr-{worker_name}` to avoid unnecessary dependencies during construction of the worker.
The worker project depends on the api but not the other way around,
so you can for example use the api in your graph code without having to install the whole worker.


## Developing your worker

Your new worker consist of two parts which are defined in the `worker_impl.py`:

1. The preabmle, declaring, your worker.
The name must be the same as the top level worker_directory
```python
worker = Worker({worker_name})
```

2. Task definitions using `@worker.task()`, make sure to use type hints, 
```python
@worker.task()
def your_worker_task(value: int) -> int:
    return value
```

To add more functionality to your worker, simply declare more `@worker.task()`s.
For this you can import existing code and wrap it in a function or copy minimal functionality there.

## Using your worker in a graph

Before you can use your worker in a graph you need to update it api with the `tkr init stubs` command.
This will generate api stubs for all functions annotated with `@worker.task()` into `api.py`.
To update the project settings make sure to `uv sync`.

You can use them as a task in the graph:
```python
def your_graph() -> GraphBuilder[TKR[int], TKR[int]]:
    g = GraphBuilder(TKR[int], TKR[int])
    out = g.task(your_worker_task(g.inputs))
    g.outputs(out)
    return g
```
If you used the `tkr init project` example, you will see a working graph code example in `tkr/graphs/main.py`.

### A note on imports

There are two ways to import your task code:
1. Using the `tkr-{worker_name}` package.
This is the recommended way, allowing you to import tasks as:
```python
from example_worker import your_worker_task
```
This will only work if you `uv add` one of the packages.
By default, the `tkr init project` will do this.

2. Importing the local python module
```python
from tkr.workers.example_worker import your_worker_task
```
This will only work if your code is locally available, and might need to run as python module (-m).

"""


def worker_api_readme(worker_name: str) -> str:
    """Generate a README.md template for a worker API.

    :param worker_name: The name of the worker.
    :type worker_name: str
    :return: The generated README.md content.
    :rtype: str
    """
    return f"""# {worker_name} Worker API

This is the api for a custom worker you just created.
The directory contains the stubs which are used during construction of a graph.

**You don't need to touch this code, it will be automatically generated.**

They can be generated using the `trk init stubs` command and are not required to be present during runtime.
They are encapsulated in a separate package `tkr-{worker_name}` to avoid unnecessary dependencies during construction of the worker.
The worker project depends on the api but not the other way around,
so you can for example use the api in your graph code without having to install the whole worker.

"""


def inputs_json() -> str:
    """Generate a workflow_inputs.json file to run sample cli command.

    :return: The generated workflow.json
    :rtype: str
    """
    return """{ "value": 1 }
"""
