[default]
extend-ignore-identifiers-re = [
  # 8 character hex identifiers in jupyter metadata
  "[a-g0-9]{8}"
]


[default.extend-identifiers]
# Internal identifiers
## Environment variable used in the docs
SER_METHOD = "SER_METHOD"

## Identifiers used for serialization
ser = "ser"
ser_from_ptype = "ser_from_ptype"

## Identifier used for map elements
map_eles = "map_eles"
eles = "eles"

# Third party identifiers
## Numpy ndarray type
NDArray = "NDArray"

## commandline flag
passin = "passin"

[default.extend-words]
Aer = "Aer"
Braket = "Braket"

# Used as a HUGR operation name.
"ine" = "ine"

