[project]
name = "tkr-substitution-worker-impl"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.11.7",
    "pytket>=2.18.1",
    "tierkreis",
    "ruff",
    "tkr-substitution-worker",
]

[tool.uv.sources]
tkr-substitution-worker = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"



[project.scripts]
tkr-substitution-worker = "tkr_substitution_worker_impl.main:main"
