[project]
name = "tkr-error-worker-impl"
version = "0.2.0"
requires-python = ">=3.12"
dependencies = ["pydantic", "tierkreis", "ruff", "tkr-error-worker"]

[tool.uv.sources]
tkr-error-worker = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"



[project.scripts]
tkr-error-worker = "tkr_error_worker_impl.main:main"
