[project]
name = "tkr-error-worker-impl"
version = "0.2.0"
requires-python = ">=3.12"
dependencies = ["pydantic", "tierkreis", "ruff", "tkr-error-worker"]

[tool.uv.sources]
tierkreis = { workspace = true }
tkr-error-worker = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"



[project.scripts]
tkr-error-worker-impl = "src.main:main"
