import _typeshed
import tierkreis_core._tierkreis_core.graph as graph
import tierkreis_core._tierkreis_core.identifiers as identifiers
import tierkreis_core._tierkreis_core.location as location
import tierkreis_core.aliases
import tierkreis_core.nodes
import typing

class CurriedNodeIndex:
    def __call__(self, /, port: str) -> identifiers.ValueRef: ...

class GraphData:
    def __eq__(self, /, other: object) -> bool: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __init__(self, /) -> None: ...
    def const(self, /, value: tierkreis_core.aliases.Value) -> identifiers.ValueRef: ...
    def eager_if_else(
        self,
        /,
        pred: identifiers.ValueRef,
        if_true: identifiers.ValueRef,
        if_false: identifiers.ValueRef,
    ) -> graph.CurriedNodeIndex: ...
    def eval(
        self,
        /,
        graph: identifiers.ExteriorRef | identifiers.ValueRef,
        inputs: typing.Mapping[tierkreis_core.aliases.PortID, identifiers.ValueRef],
    ) -> graph.CurriedNodeIndex: ...
    @property
    def fixed_inputs(self, /) -> typing.Any: ...
    @classmethod
    def from_dict(cls, /, obj: typing.Any) -> graph.GraphData: ...
    def func(
        self,
        /,
        function_name: str | None,
        inputs: typing.Mapping[tierkreis_core.aliases.PortID, identifiers.ValueRef],
    ) -> graph.CurriedNodeIndex: ...
    def get_nodedef(self, /, node_idx: identifiers.NodeIndex) -> graph.NodeDef: ...
    def graph_outputs(
        self, /
    ) -> dict[tierkreis_core.aliases.PortID, identifiers.NodeIndex] | None: ...
    def if_else(
        self,
        /,
        pred: identifiers.ValueRef,
        if_true: identifiers.ValueRef,
        if_false: identifiers.ValueRef,
    ) -> graph.CurriedNodeIndex: ...
    def input(self, /, name: str) -> identifiers.ValueRef: ...
    def is_empty(self, /) -> bool: ...
    def loop(
        self,
        /,
        graph: identifiers.ExteriorRef | identifiers.ValueRef,
        inputs: typing.Mapping[tierkreis_core.aliases.PortID, identifiers.ValueRef],
        continue_port: tierkreis_core.aliases.PortID,
        name: str | None = None,
    ) -> graph.CurriedNodeIndex: ...
    def map(
        self,
        /,
        graph: identifiers.ExteriorRef | identifiers.ValueRef,
        inputs: typing.Mapping[tierkreis_core.aliases.PortID, identifiers.ValueRef],
    ) -> graph.CurriedNodeIndex: ...
    def model_dump(self, /) -> typing.Any: ...
    def model_dump_json(self, /) -> str: ...
    @classmethod
    def model_load(cls, /, obj: typing.Any) -> graph.GraphData: ...
    @classmethod
    def model_load_json(cls, /, s: str) -> graph.GraphData: ...
    @property
    def nodes(self, /) -> list[NodeDef]: ...
    def output(
        self,
        /,
        inputs: typing.Mapping[tierkreis_core.aliases.PortID, identifiers.ValueRef],
    ) -> None: ...
    def output_idx(self, /) -> identifiers.NodeIndex | None: ...
    def outputs(
        self, /, node_index: identifiers.NodeIndex
    ) -> dict[tierkreis_core.aliases.PortID, identifiers.NodeIndex] | None: ...
    def query_node_description(self, /, loc: location.Loc) -> graph.NodeDescription: ...
    def remaining_inputs(
        self, /, provided_inputs: typing.Set[tierkreis_core.aliases.PortID]
    ) -> set[tierkreis_core.aliases.PortID]: ...
    def to_dict(self, /) -> typing.Any: ...

class NodeDef:
    Func = tierkreis_core.nodes.NodeDef_Func
    Eval = tierkreis_core.nodes.NodeDef_Eval
    Loop = tierkreis_core.nodes.NodeDef_Loop
    Map = tierkreis_core.nodes.NodeDef_Map
    Const = tierkreis_core.nodes.NodeDef_Const
    IfElse = tierkreis_core.nodes.NodeDef_IfElse
    EagerIfElse = tierkreis_core.nodes.NodeDef_EagerIfElse
    Input = tierkreis_core.nodes.NodeDef_Input
    Output = tierkreis_core.nodes.NodeDef_Output

    def __eq__(self, /, other: object) -> bool: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @property
    def in_edges(
        self, /
    ) -> dict[
        tierkreis_core.aliases.PortID, identifiers.ValueRef | identifiers.ExteriorRef
    ]: ...
    @property
    def inputs(
        self, /
    ) -> dict[
        tierkreis_core.aliases.PortID, identifiers.ValueRef | identifiers.ExteriorRef
    ]: ...
    def model_dump_json(self, /) -> str: ...
    @classmethod
    def model_load_json(cls, /, s: str) -> graph.NodeDef: ...

class NodeDescription:
    def __eq__(self, /, other: object) -> bool: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __init__(
        self,
        /,
        definition: graph.NodeDef,
        outputs: typing.Mapping[
            tierkreis_core.aliases.PortID, identifiers.NodeIndex
        ] = ...,
        outer_graph: graph.GraphData | None = None,
    ) -> None: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @property
    def definition(self, /) -> graph.NodeDef: ...
    @classmethod
    def from_dict(cls, /, obj: typing.Any) -> graph.NodeDescription: ...
    def model_dump(self, /) -> typing.Any: ...
    def model_dump_json(self, /) -> str: ...
    @classmethod
    def model_load(cls, /, obj: typing.Any) -> graph.NodeDescription: ...
    @classmethod
    def model_load_json(cls, /, s: str) -> graph.NodeDescription: ...
    @property
    def outer_graph(self, /) -> graph.GraphData | None: ...
    @property
    def outputs(
        self, /
    ) -> dict[tierkreis_core.aliases.PortID, identifiers.NodeIndex]: ...
    def to_dict(self, /) -> typing.Any: ...

def new_eval_root(
    inputs: typing.Mapping[
        tierkreis_core.aliases.PortID, identifiers.ExteriorRef | identifiers.ValueRef
    ],
) -> graph.NodeDef: ...
def __getattr__(name: str) -> _typeshed.Incomplete: ...
