import _typeshed
import tierkreis_core._tierkreis_core.identifiers as identifiers
import typing

class ExteriorRef:
    def __eq__(self, /, other: object) -> bool: ...
    def __iter__(self, /) -> typing.Any: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __init__(self, /, port_id: str) -> None: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @property
    def port_id(self, /) -> str: ...

class NodeIndex:
    def __eq__(self, /, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __init__(self, /, val: int) -> None: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...

class ValueRef:
    def __eq__(self, /, other: object) -> bool: ...
    def __iter__(self, /) -> typing.Any: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __init__(self, /, node_index: identifiers.NodeIndex, port_id: str) -> None: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @property
    def node_index(self, /) -> identifiers.NodeIndex: ...
    @property
    def port_id(self, /) -> str: ...

def __getattr__(name: str) -> _typeshed.Incomplete: ...
