import _typeshed
import tierkreis_core.steps
import tierkreis_core._tierkreis_core.identifiers as identifiers
import tierkreis_core._tierkreis_core.location as location
import typing

class Loc:
    def L(self, /, loop_index: int) -> location.Loc: ...
    def M(self, /, map_index: int) -> location.Loc: ...
    def N(self, /, node_index: identifiers.NodeIndex | int) -> location.Loc: ...
    def __eq__(self, /, other: object) -> bool: ...
    def __fspath__(self, /) -> str: ...
    @classmethod
    def __get_pydantic_core_schema__(
        cls, /, _source: typing.Any, _handler: typing.Any
    ) -> typing.Any: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __init__(self, /, k: str = "-") -> None: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @staticmethod
    def _validate(value: location.Loc | str) -> location.Loc: ...
    def extend_from_ref(
        self, /, value_ref: identifiers.ExteriorRef | identifiers.ValueRef
    ) -> location.Loc: ...
    def exterior(self, /) -> location.Loc: ...
    @staticmethod
    def from_steps(steps: typing.Sequence[NodeStep]) -> location.Loc: ...
    def is_root_loc(self, /) -> bool: ...
    def last_step_exterior(self, /) -> bool: ...
    def parent(self, /) -> Loc | None: ...
    def partial_locs(self, /) -> typing.Any: ...
    def peek_index(self, /) -> int | None: ...
    def pop_first(self, /) -> tuple[NodeStep, Loc]: ...
    def pop_last(self, /) -> tuple[NodeStep, Loc]: ...
    def startswith(self, /, other: location.Loc) -> bool: ...
    def steps(self, /) -> list[Loc]: ...

class NodeStep:
    Root = tierkreis_core.steps.NodeStep_Root
    Node = tierkreis_core.steps.NodeStep_Node
    Loop = tierkreis_core.steps.NodeStep_Loop
    Map = tierkreis_core.steps.NodeStep_Map
    Exterior = tierkreis_core.steps.NodeStep_Exterior

    def __eq__(self, /, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __iter__(self, /) -> typing.Any: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __init__(self, /, steps: str) -> None: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    def is_root(self, /) -> bool: ...

def __getattr__(name: str) -> _typeshed.Incomplete: ...
