/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MonitorIndexRouteImport } from './routes/monitor/index'
import { Route as BuilderIndexRouteImport } from './routes/builder/index'
import { Route as WorkflowsWidNodesLocIndexRouteImport } from './routes/workflows/_.$wid.nodes.$loc/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorIndexRoute = MonitorIndexRouteImport.update({
  id: '/monitor/',
  path: '/monitor/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderIndexRoute = BuilderIndexRouteImport.update({
  id: '/builder/',
  path: '/builder/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsWidNodesLocIndexRoute =
  WorkflowsWidNodesLocIndexRouteImport.update({
    id: '/workflows/_/$wid/nodes/$loc/',
    path: '/workflows/$wid/nodes/$loc/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder/': typeof BuilderIndexRoute
  '/monitor/': typeof MonitorIndexRoute
  '/workflows/$wid/nodes/$loc/': typeof WorkflowsWidNodesLocIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderIndexRoute
  '/monitor': typeof MonitorIndexRoute
  '/workflows/$wid/nodes/$loc': typeof WorkflowsWidNodesLocIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder/': typeof BuilderIndexRoute
  '/monitor/': typeof MonitorIndexRoute
  '/workflows/_/$wid/nodes/$loc/': typeof WorkflowsWidNodesLocIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/builder/' | '/monitor/' | '/workflows/$wid/nodes/$loc/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/builder' | '/monitor' | '/workflows/$wid/nodes/$loc'
  id:
    | '__root__'
    | '/'
    | '/builder/'
    | '/monitor/'
    | '/workflows/_/$wid/nodes/$loc/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderIndexRoute: typeof BuilderIndexRoute
  MonitorIndexRoute: typeof MonitorIndexRoute
  WorkflowsWidNodesLocIndexRoute: typeof WorkflowsWidNodesLocIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor/': {
      id: '/monitor/'
      path: '/monitor'
      fullPath: '/monitor/'
      preLoaderRoute: typeof MonitorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/': {
      id: '/builder/'
      path: '/builder'
      fullPath: '/builder/'
      preLoaderRoute: typeof BuilderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/_/$wid/nodes/$loc/': {
      id: '/workflows/_/$wid/nodes/$loc/'
      path: '/workflows/$wid/nodes/$loc'
      fullPath: '/workflows/$wid/nodes/$loc/'
      preLoaderRoute: typeof WorkflowsWidNodesLocIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderIndexRoute: BuilderIndexRoute,
  MonitorIndexRoute: MonitorIndexRoute,
  WorkflowsWidNodesLocIndexRoute: WorkflowsWidNodesLocIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
