[project]
name = "tkr-pytket-worker"
version = "0.2.1"
description = "The api for the Tierkreis pytket worker."
requires-python = ">=3.12"
authors = [ {name = "Quantinuum Tierkreis Team"} ]
dependencies = [
    "tierkreis",
]

[tool.uv.sources]
tierkreis = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel.force-include]
"api.py" = "pytket_worker.py"
