import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import { useQuery } from "@tanstack/react-query";
import type { paths } from "./api_stubs"; // generated by openapi-typescript
import type {
  MonitoringSummary,
  NewRunResponse,
  RuntimeInfo,
  TraceSpan,
  WorkflowPorts,
  WorkflowSummary,
} from "./api_types";

const fetchClient = createFetchClient<paths>({
  baseUrl: import.meta.env.BASE_URL,
  headers: { Accept: "application/json" },
});
const $api = createClient(fetchClient);

export const fetchLogs = async (workflow_id: string) => {
  const res = await fetchClient.GET("/api/workflows/{workflow_id}/logs", {
    params: { path: { workflow_id } },
    parseAs: "text",
  });
  return res.error ? "Failed to fetch logs." : res.data || "No logs.";
};

export const fetchOutput = async (
  workflow_id: string,
  node_location_str: string,
  port_name: string,
) => {
  const res = await fetchClient.GET(
    "/api/workflows/{workflow_id}/nodes/{node_location_str}/outputs/{port_name}",
    {
      params: { path: { workflow_id, node_location_str, port_name } },
      parseAs: "text",
    },
  );
  return res.error ? "Failed to fetch output." : res.data;
};

export const fetchOutputs = async (
  workflow_id: string,
  node_location_str: string,
) => {
  const res = await fetchClient.GET(
    "/api/workflows/{workflow_id}/nodes/{node_location_str}/outputs",
    {
      params: { path: { workflow_id, node_location_str } },
      parseAs: "text",
    },
  );
  return res.error ? "Failed to fetch output." : res.data;
};

export const fetchErrors = async (
  workflow_id: string,
  node_location_str: string,
) => {
  const params = { path: { workflow_id, node_location_str } };
  const res = await fetchClient.GET(
    "/api/workflows/{workflow_id}/nodes/{node_location_str}/errors",
    { params, parseAs: "text" },
  );
  return res.data ?? "No errors.";
};

export const fetchNodeLogs = async (
  workflow_id: string,
  node_location_str: string,
) => {
  const params = { path: { workflow_id, node_location_str } };
  const res = await fetchClient.GET(
    "/api/workflows/{workflow_id}/nodes/{node_location_str}/logs",
    { params, parseAs: "text" },
  );
  return res.data ?? "No logs.";
};

export const restartNode = async (
  workflow_id: string,
  node_location_str: string,
): Promise<string[]> => {
  const params = { path: { workflow_id, node_location_str } };
  const res = await fetchClient.POST(
    "/api/workflows/{workflow_id}/nodes/{node_location_str}/restart",
    { params },
  );
  if (res.error) {
    console.log("Failed to restart node.");
    return [];
  }
  return res.data;
};

export const useInfoQuery = () => $api.useQuery("get", "/api/info");
export const useWorkflowsQuery = () => $api.useQuery("get", "/api/workflows/");
export const useLogsQuery = (workflow_id: string) =>
  $api.useQuery("get", "/api/workflows/{workflow_id}/logs", {
    params: { path: { workflow_id } },
    parseAs: "text",
  });
export const useEvalQuery = (workflow_id: string, openEvals: string[]) =>
  $api.useQuery("get", "/api/workflows/{workflow_id}/graphs", {
    params: { path: { workflow_id }, query: { locs: openEvals } },
  });

// Served only by the Rust runtime server; not (yet) part of the generated
// openapi stubs, so fetched and typed by hand.
const base = () => import.meta.env.BASE_URL;

const getJson = async <T>(path: string): Promise<T> => {
  const res = await fetch(`${base()}${path}`);
  if (!res.ok) throw new Error(`Failed to fetch ${path}.`);
  return res.json();
};

const postJson = async <T>(path: string, body?: unknown): Promise<T> => {
  const res = await fetch(`${base()}${path}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: body ? JSON.stringify(body) : undefined,
  });
  if (!res.ok) throw new Error(`Failed to POST ${path}.`);
  return res.json();
};

export const useWorkflowsSummaryQuery = () =>
  useQuery({
    queryKey: ["monitor", "workflows"],
    queryFn: () => getJson<WorkflowSummary[]>("api/monitor/workflows"),
    refetchInterval: 5000,
  });

export const useRuntimeInfoQuery = () =>
  useQuery({
    queryKey: ["runtime"],
    queryFn: () => getJson<RuntimeInfo>("api/runtime"),
    refetchInterval: 10000,
  });

export const useRunTraceQuery = (run_id: string, attempt: number) =>
  useQuery({
    queryKey: ["trace", run_id, attempt],
    queryFn: () =>
      getJson<TraceSpan[]>(`api/runs/${run_id}/attempts/${attempt}/trace`),
    enabled: !!run_id,
  });

export const useWorkflowInputNamesQuery = (workflow_id: string) =>
  useQuery({
    queryKey: ["workflow-input-names", workflow_id],
    queryFn: () =>
      getJson<string[]>(`api/workflows/${workflow_id}/input_names`),
    enabled: !!workflow_id,
  });

export const useWorkflowPortsQuery = (workflow_id: string) =>
  useQuery({
    queryKey: ["workflow-ports", workflow_id],
    queryFn: () => getJson<WorkflowPorts>(`api/workflows/${workflow_id}/ports`),
    enabled: !!workflow_id,
  });

export const startNewRun = (
  workflow_id: string,
  inputs: Record<string, unknown>,
) => postJson<NewRunResponse>(`api/workflows/${workflow_id}/runs`, { inputs });

export const startNewAttempt = (run_id: string) =>
  postJson<NewRunResponse>(`api/runs/${run_id}/attempts`);

export const useMonitoringSummaryQuery = () =>
  useQuery({
    queryKey: ["monitor"],
    queryFn: () => getJson<MonitoringSummary>("api/monitor"),
    refetchInterval: 5000,
  });
