import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./api_stubs"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
  baseUrl: import.meta.env.BASE_URL,
  headers: { Accept: "application/json" },
});
const $api = createClient(fetchClient);

export const fetchLogs = async (workflow_id: string) => {
  const res = await fetchClient.GET("/api/workflows/{workflow_id}/logs", {
    params: { path: { workflow_id } },
    parseAs: "text",
  });
  return res.error ? "Failed to fetch logs." : res.data || "No logs.";
};

export const fetchErrors = async (
  workflow_id: string,
  node_location_str: string
) => {
  const params = { path: { workflow_id, node_location_str } };
  const res = await fetchClient.GET(
    "/api/workflows/{workflow_id}/nodes/{node_location_str}/errors",
    { params, parseAs: "text" }
  );
  return res.data ?? "No errors.";
};

export const useWorkflowsQuery = () => $api.useQuery("get", "/api/workflows/");
export const useLogsQuery = (workflow_id: string) =>
  $api.useQuery("get", "/api/workflows/{workflow_id}/logs", {
    params: { path: { workflow_id } },
    parseAs: "text",
  });
export const useEvalQuery = (workflow_id: string, openEvals: string[]) =>
  $api.useQuery("get", "/api/workflows/{workflow_id}/graphs", {
    params: { path: { workflow_id }, query: { locs: openEvals } },
  });
