import type { paths } from "./api_stubs"; // generated by openapi-typescript

export type WorkflowDisplay =
  paths["/api/workflows/"]["get"]["responses"]["200"]["content"]["application/json"][0];
export type PyGraph =
  paths["/api/workflows/{workflow_id}/graphs"]["get"]["responses"]["200"]["content"]["application/json"]["graphs"][0];
export type PyEdge = PyGraph["edges"][0];
export type PyNode = PyGraph["nodes"][0];
