[project]
name = "tkr-qulacs-worker-impl"
description = "A Tierkreis worker for Qulacs."
version = "0.2.0"
authors = [ {name = "Quantinuum Tierkreis Team"} ]
requires-python = ">=3.12"
dependencies = [
    "pytket-qulacs>=0.41.0",
    "tierkreis",
    "tkr-qulacs-worker"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"



[tool.uv.sources]
tierkreis = { workspace = true }
tkr-qulacs-worker = { workspace = true }

[project.scripts]
tkr-qulacs-worker = "tkr_qulacs_worker_impl.main:main"
