use miette::{Context, IntoDiagnostic, miette};
use regex::Regex;
/// SLURM specific functionality
use std::{
    os::unix::{fs::PermissionsExt, process::ExitStatusExt},
    path::Path,
    process::{ExitStatus, Stdio},
    time::Duration,
};
use tokio::{io::AsyncReadExt, process::Command};

use crate::executor::hpc::BackgroundTaskPlan;

/// Poll slurm for COMPLETED or FAILED
pub async fn poll_slurm_status(
    job_id: &str,
    poll_interval: Duration,
    max_timeout: Duration,
) -> miette::Result<ExitStatus> {
    let start = std::time::Instant::now();

    loop {
        let sacct_output =
            Command::new("/Users/philipp.seitz/Projects/tierkreis/infra/slurm_local/sacct")
                .arg("-j")
                .arg(job_id)
                .arg("--format=State")
                .arg("-X")
                .output()
                .await
                .into_diagnostic()
                .wrap_err("Failed to run sacct command")?;

        if sacct_output.status.success() {
            let output_str = String::from_utf8_lossy(&sacct_output.stdout);
            if output_str.contains("COMPLETED") {
                return Ok(ExitStatus::from_raw(0));
            } else if output_str.contains("FAILED") {
                return Err(miette!("Job failed according to sacct output"));
            } // TODO: terminate on other states
        }
        if start.elapsed() > max_timeout {
            return Err(miette!(
                "Polling timed out while waiting for job completion"
            ));
        }

        tokio::time::sleep(poll_interval).await;
    }
}

/// Parse the output of the sbatch command to extract the job ID
pub fn parse_and_extract_job_id(
    child: &mut tokio::process::Child,
) -> tokio::task::JoinHandle<Result<String, miette::Error>> {
    let mut stdout = child.stdout.take().unwrap();
    tokio::spawn(async move {
        let mut stdout_out = String::new();
        let _ = stdout.read_to_string(&mut stdout_out).await;
        // TODO: Replace with the correct regex pattern
        let re = Regex::new(r"job\s+(\d+)")
            .into_diagnostic()
            .wrap_err("Failed to compile job ID regex")?;

        re.captures(&stdout_out)
            .and_then(|caps| caps.get(1))
            .map(|m| m.as_str().to_string())
            .ok_or_else(|| miette!("Failed to extract job ID from submission output"))
    })
}

/// Submit a job to slurm using the sbatch command
pub fn submit_job(job_script_path: &Path) -> Result<tokio::process::Child, miette::Error> {
    let child = Command::new("/Users/philipp.seitz/Projects/tierkreis/infra/slurm_local/sbatch")
        .arg(job_script_path)
        //.arg("--help")
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .into_diagnostic()?;
    Ok(child)
}

/// Write a job script for slurm based on the provided `BackgroundTaskPlan`
pub fn write_jobscript(task: &BackgroundTaskPlan, script_path: &Path) -> miette::Result<()> {
    // TODO: Write jobscript
    let args_path = &task.worker_args.as_path().to_string_lossy();
    let base_path = task
        .worker_args
        .parent()
        .unwrap_or_else(|| Path::new("."))
        .to_string_lossy();
    let script_content = format!(
        r"#!/bin/bash
#
# SLURM Job Script generated by TIERKREIS

# --- Core Job Specifications ---
#SBATCH --job-name=test_job
#SBATCH --time=00:15:00
#SBATCH --nodes=2
#SBATCH --cpus-per-task=1
#SBATCH --gpus-per-node=0

# --- User Details ---
#SBATCH --account=test_usr

# --- Output and Error Handling ---

# --- MPI ---
#SBATCH --ntasks-per-node=1

# --- User-Specific Arguments ---
#SBATCH --open-mode=append

#SBATCH --output=%A.out 
#SBATCH --error=%A.err

# --- Environment Setup ---
export OMPI_ALLOW_RUN_AS_ROOT=1
export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
export TKR_DIR={base_path}

# --- User Command ---
eval mpiexec /root/.local/bin/uv run /mpi_worker/main.py {args_path}
"
    );
    std::fs::write(script_path, script_content)
        .into_diagnostic()
        .wrap_err("Failed to write job script")?;
    std::fs::set_permissions(script_path, std::fs::Permissions::from_mode(0o755))
        .into_diagnostic()
        .wrap_err("Failed to set job script permissions")?;
    Ok(())
}
