[project]
name = "tkr-nexus-worker-impl"
version = "0.2.1"
description = "A Tierkreis worker for interacting with Nexus."
authors = [ {name = "Quantinuum Tierkreis Team"} ]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "tierkreis",
    "qnexus==0.47.0",
    "tkr-nexus-worker",
    "hugr"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.uv.sources]
tkr-nexus-worker = { workspace = true }

[project.scripts]
tkr-nexus-worker = "tkr_nexus_worker_impl.main:main"
