#!/bin/bash
SCRIPT_FILE=$(basename "$1")

NODE_PATH=$(sed -n -E '$ s#.*([0-9a-fA-F-]{36}/[^/]+)/definition$#\1#p' "$1")
WORKFLOW_ID=$(echo "$NODE_PATH" | cut -d'/' -f1)
docker cp "$1" slurmctld:/data/"$SCRIPT_FILE"
docker exec slurmctld sh -c 'rm -rf /data/*.log && \
ln -s $HOME/.tierkreis/checkpoints/$2/logs /data/logs.log && \
ln -s $HOME/.tierkreis/checkpoints/$3/logs /data/errors.log  && \
sbatch --output=logs.log --error=errors.log --chdir=/data /data/$1' sh "$SCRIPT_FILE" "$WORKFLOW_ID" "$NODE_PATH"
