#!/bin/bash
SCRIPT_FILE=$(basename "$1")

# This emulates the sbatch command assuming .tkr is in $HOME
# Rewrites all occurrences of $HOME in the script to /root,
# which is where the home directory is mounted in the container
docker cp "$1" slurmctld:/data/"$SCRIPT_FILE"
docker exec slurmctld sh -c 'sed -i "s|$2|/root|g" /data/$1 && \
sbatch /data/$1' sh "$SCRIPT_FILE" "$HOME"
