[project]
name = "tkr-multiple-outputs-worker-impl"
version = "0.2.0"
description = "A tierkreis worker implementation."
requires-python = ">=3.12"
dependencies = [
    "tierkreis",
    "tkr-multiple-outputs-worker",
]

[tool.uv.sources]
tkr-multiple-outputs-worker = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.16.1",
]

[project.scripts]
tkr-multiple-outputs-worker = "tkr_multiple_outputs_worker_impl.main:main"
