"""Handwritten stub for alias types that cannot be generated by pyO3 introspection.

See: https://github.com/PyO3/pyo3/issues/5137 for progress.

"""

from typing import Mapping, Sequence

from tierkreis_core import GraphData

type PortID = str
# Constant values
type Value = (
    int | float | bool | str | bytes | Sequence[Value] | Mapping[str, Value] | GraphData
)
