"""Handwritten stub for Node enum types that cannot be generated by pyO3 introspection.

See: https://github.com/PyO3/pyo3/issues/5137 for progress.

"""

from typing import Mapping
import tierkreis_core
import tierkreis_core._tierkreis_core.identifiers as identifiers
from tierkreis_core import NodeDef

class NodeDef_Func(NodeDef):
    def __init__(
        self,
        name: str,
        inputs: Mapping[
            tierkreis_core.aliases.PortID,
            identifiers.ExteriorRef | identifiers.ValueRef,
        ],
    ) -> None: ...
    @property
    def name(self, /) -> str: ...
    @property
    def inputs(
        self, /
    ) -> dict[
        tierkreis_core.aliases.PortID, identifiers.ExteriorRef | identifiers.ValueRef
    ]: ...

class NodeDef_Eval(NodeDef):
    def __init__(
        self,
        body: identifiers.ExteriorRef | identifiers.ValueRef,
        inputs: Mapping[
            tierkreis_core.aliases.PortID,
            identifiers.ExteriorRef | identifiers.ValueRef,
        ],
    ) -> None: ...
    @property
    def body(self, /) -> identifiers.ExteriorRef | identifiers.ValueRef: ...
    @property
    def inputs(
        self, /
    ) -> dict[
        tierkreis_core.aliases.PortID, identifiers.ExteriorRef | identifiers.ValueRef
    ]: ...

class NodeDef_Loop(NodeDef):
    def __init__(
        self,
        body: identifiers.ExteriorRef | identifiers.ValueRef,
        inputs: Mapping[
            tierkreis_core.aliases.PortID,
            identifiers.ExteriorRef | identifiers.ValueRef,
        ],
        continue_port: tierkreis_core.aliases.PortID,
        name: str | None = None,
    ) -> None: ...
    @property
    def name(self, /) -> str | None: ...
    @property
    def body(self, /) -> identifiers.ExteriorRef | identifiers.ValueRef: ...
    @property
    def inputs(
        self, /
    ) -> dict[
        tierkreis_core.aliases.PortID, identifiers.ExteriorRef | identifiers.ValueRef
    ]: ...
    @property
    def continue_port(self, /) -> tierkreis_core.aliases.PortID: ...

class NodeDef_Map(NodeDef):
    def __init__(
        self,
        body: identifiers.ExteriorRef | identifiers.ValueRef,
        inputs: Mapping[
            tierkreis_core.aliases.PortID,
            identifiers.ExteriorRef | identifiers.ValueRef,
        ],
    ) -> None: ...
    @property
    def body(self, /) -> identifiers.ExteriorRef | identifiers.ValueRef: ...
    @property
    def inputs(
        self, /
    ) -> dict[
        tierkreis_core.aliases.PortID, identifiers.ExteriorRef | identifiers.ValueRef
    ]: ...

class NodeDef_Const(NodeDef):
    def __init__(self, value: tierkreis_core.aliases.Value) -> None: ...
    @property
    def value(self, /) -> tierkreis_core.aliases.Value: ...

class NodeDef_IfElse(NodeDef):
    def __init__(
        self,
        pred: identifiers.ValueRef,
        if_true: identifiers.ValueRef,
        if_false: identifiers.ValueRef,
    ) -> None: ...
    @property
    def pred(self, /) -> identifiers.ValueRef: ...
    @property
    def if_true(self, /) -> identifiers.ValueRef: ...
    @property
    def if_false(self, /) -> identifiers.ValueRef: ...

class NodeDef_EagerIfElse(NodeDef):
    def __init__(
        self,
        pred: identifiers.ValueRef,
        if_true: identifiers.ValueRef,
        if_false: identifiers.ValueRef,
    ) -> None: ...
    @property
    def pred(self, /) -> identifiers.ValueRef: ...
    @property
    def if_true(self, /) -> identifiers.ValueRef: ...
    @property
    def if_false(self, /) -> identifiers.ValueRef: ...

class NodeDef_Input(NodeDef):
    def __init__(self, name: tierkreis_core.aliases.PortID) -> None: ...
    @property
    def name(self, /) -> tierkreis_core.aliases.PortID: ...

class NodeDef_Output(NodeDef):
    def __init__(
        self, outputs: Mapping[tierkreis_core.aliases.PortID, identifiers.ValueRef]
    ) -> None: ...
    @property
    def outputs(
        self, /
    ) -> dict[tierkreis_core.aliases.PortID, identifiers.ValueRef]: ...
