"""Handwritten stub for Node enum types that cannot be generated by pyO3 introspection.

See: https://github.com/PyO3/pyo3/issues/5137 for progress.

"""

from tierkreis_core import NodeStep, NodeIndex

class NodeStep_Root(NodeStep): ...

class NodeStep_Node(NodeStep):
    @property
    def node_index(self, /) -> NodeIndex: ...

class NodeStep_Loop(NodeStep):
    @property
    def loop_index(self, /) -> int: ...

class NodeStep_Map(NodeStep):
    @property
    def map_index(self, /) -> int: ...

class NodeStep_Exterior(NodeStep): ...
