[project]
name = "tierkreis"
description = "Python client and utilities for tierkreis."
readme = "README.md"
version = "2.0.12"
authors = [
    { name = "Seyon Sivarajah", email = "seyon.sivarajah@quantinuum.com" },
    { name = "Lukas Heidemann", email = "lukas.heidemann@quantinuum.com" },
    { name = "John Children", email = "john.children@quantinuum.com" },
    { name = "Alan Lawrence", email = "alan.lawrence@quantinuum.com" },
    { name = "Matthew Burke", email = "matthew.burke@quantinuum.com" },
    { name = "Philipp Seitz", email = "philipp.seitz@quantinuum.com" },
]

requires-python = ">=3.12"
dependencies = [
    "hugr",
    "pydantic~=2.5",
]

[project.optional-dependencies]
hpc = [
    "psij-python>=0.9.11",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "pytest",
    "guppylang",
    "qnexus",
]
build = ["build[uv]"]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.ruff]
target-version = "py312"
extend-exclude = []
format.preview = true

[tool.pyright]
include = ["."]
exclude = []
ignore = []

[tool.maturin]
module-name = "tierkreis._tierkreis"

# [project.scripts]
# tkr = "tierkreis.cli.tkr:main"
