[project]
name = "tierkreis"
description = "The Tierkreis Scientific Workflow Management System."
readme = "README.md"
version = "2.1.1"
authors = [
    { name = "Seyon Sivarajah", email = "seyon.sivarajah@quantinuum.com" },
    { name = "Lukas Heidemann", email = "lukas.heidemann@quantinuum.com" },
    { name = "John Children", email = "john.children@quantinuum.com" },
    { name = "Alan Lawrence", email = "alan.lawrence@quantinuum.com" },
    { name = "Matthew Burke", email = "matthew.burke@quantinuum.com" },
    { name = "Philipp Seitz", email = "philipp.seitz@quantinuum.com" },
]
license = {file = "LICENSE"}

requires-python = ">=3.12"
dependencies = [
    "hugr",
    "opentelemetry-exporter-otlp-proto-grpc>=1.44.0",
    "opentelemetry-sdk>=1.44.0",
    "pydantic~=2.5",
]

[project.optional-dependencies]
stubs = [
    "ruff>=0.16.4",
]
hpc = [
    "psij-python>=0.9.11",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "pytest",
    "guppylang >=0.21.0",
    "qnexus",
]
build = ["build[uv]"]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.ruff]
target-version = "py312"
extend-exclude = []
format.preview = true

[tool.pyright]
include = ["."]
exclude = []
ignore = []

[tool.maturin]
module-name = "tierkreis._tierkreis"

[tool.maturin.generate-ci.github]
# generate-ci has been modified a bit so this isn't going to re-create the
# github actions workflow directly.
trusted-publishing = true
publishing-environment = "pypi"

[project.scripts]
tkr-builtins = "tierkreis.builtins.main:main"
tkr = "tierkreis.cli.tkr:main"

[project.urls]
repository = "https://github.com/Quantinuum/tierkreis"
documentation = "https://quantinuum.github.io/tierkreis/"
