//! Embedded templates used by project initialization.

pub const WORKER_README: &str = r"# {{worker_title}} Worker

This worker was generated by `tkr init worker`. Its implementation and API are
separate packages so graph construction does not install runtime dependencies.

After changing task signatures, run `tkr generate stubs` from the project root.
";

pub const API_README: &str = r"# {{worker_title}} Worker API

This package contains generated graph-construction types. Do not edit `api.py`
by hand; regenerate it with `tkr generate stubs`.
";

pub const WORKER_PYPROJECT: &str = r#"[project]
name = "tkr-{{dist_name}}-impl"
version = "0.1.0"
description = "A Tierkreis worker implementation."
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["tierkreis"]

[tool.uv.workspace]
members = ["api"]

[tool.uv.sources]
tkr-{{dist_name}} = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
tkr-{{dist_name}} = "tkr_{{module_name}}_impl.main:main"
"#;

pub const API_PYPROJECT: &str = r#"[project]
name = "tkr-{{dist_name}}"
version = "0.1.0"
description = "A Tierkreis worker API."
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["tierkreis"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel.force-include]
"api.py" = "{{module_name}}.py"
"#;

pub const WORKER_MAIN: &str = r#"# Generated by tkr. Do not modify.
from sys import argv

from tkr_{{module_name}}_impl import worker


def main() -> None:
    worker.app(argv)


if __name__ == "__main__":
    main()
"#;

pub const WORKER_IMPL: &str = r#"from tierkreis import Worker

worker = Worker("{{module_name}}")


@worker.task()
def your_worker_task(value: int) -> int:
    return value
"#;

pub const API_STUB: &str = r#""""Code generated from {{module_name}} namespace. Please do not edit."""

from typing import NamedTuple

from tierkreis.controller.data.models import TKR


class your_worker_task(NamedTuple):
    value: TKR[int]

    @staticmethod
    def out() -> type[TKR[int]]:
        return TKR[int]

    @property
    def namespace(self) -> str:
        return "{{module_name}}"
"#;

pub const EXTERNAL_API_PLACEHOLDER: &str = r#""""API placeholder for {{module_name}}.

Run `tkr generate stubs` to generate this module from the TypeSpec schema.
"""
"#;

pub const EXTERNAL_IDL: &str = r"model YourModel {
    value: int
}

interface {{module_name}} {
    your_function(value: int): YourModel;
}
";

pub const DEFAULT_GRAPH: &str = r#"from typing import NamedTuple
from pathlib import Path
from uuid import UUID

from tierkreis.builder import Graph
from tierkreis.controller import run_graph
from tierkreis.models import TKR, Workflow
from tierkreis.executor import UvExecutor
from tierkreis.storage import FileStorage, read_outputs

from tkr.workers.{{module_name}} import your_worker_task


class GraphInputs(NamedTuple):
    value: TKR[int]


class GraphOutputs(NamedTuple):
    value: TKR[int]


def workflow() -> Workflow[GraphInputs, GraphOutputs]:
    graph = Graph(GraphInputs, GraphOutputs)
    result = graph.task(your_worker_task(graph.inputs.value))
    return graph.finish_with_outputs(GraphOutputs(value=result))


def main() -> None:
    graph = workflow()
    storage = FileStorage(workflow_id=UUID(int=12345), name="your_workflow")
    executor = UvExecutor(Path(__file__).parent.parent / "workers", storage.logs_path)
    storage.clean_graph_files()
    run_graph(storage, executor, graph, {"value": 1})
    print("Value is:", read_outputs(graph, storage))


if __name__ == "__main__":
    main()
"#;

pub const INPUTS: &str = "{ \"value\": 1 }\n";

pub const PROJECT_PYPROJECT: &str = r#"[project]
name = "tierkreis-project"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["tierkreis"]

[tool.uv.workspace]
members = [
    "tkr/workers/*",
    "tkr/workers/*/api",
]
"#;

pub fn render(template: &str, module_name: &str, dist_name: &str) -> String {
    template
        .replace("{{module_name}}", module_name)
        .replace("{{dist_name}}", dist_name)
        .replace("{{worker_title}}", &module_name.replace('_', " "))
}
