[project]
name = "tkr-hello-world-worker-impl"
version = "0.2.0"
requires-python = ">=3.12"
dependencies = ["tierkreis", "ruff", "tkr-hello-world-worker"]

[tool.uv.sources]
tkr-hello-world-worker = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
tkr-hello-world-worker = "tkr_hello_world_worker_impl.main:main"

