[project]
name = "tkr-hello-world-worker-impl"
version = "0.2.0"
requires-python = ">=3.12"
dependencies = ["tierkreis", "ruff", "tkr-hello-world-worker"]

[tool.uv.sources]
tierkreis = { workspace = true }
tkr-hello-world-worker = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[project.scripts]
tkr-hello-world-worker = "src.main:main"

