[project]
name = "tkr-scipy-worker-impl"
version = "0.2.0"
requires-python = ">=3.12"
dependencies = [
    "scipy>=1.18.1",
    "tierkreis>=2.0.10",
    "ruff",
    "tkr-scipy-worker",
]

[tool.uv.sources]
tkr-scipy-worker = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"



[project.scripts]
tkr-scipy-worker = "tkr_scipy_worker_impl.main:main"
