[project]
name = "tkr-quantinuum-worker-impl"
version = "0.2.1"
description = "A Tierkreis worker for compilation of quanitnuum backends."
authors = [ {name = "Quantinuum Tierkreis Team"} ]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytket-quantinuum>=0.57.0",
    "qnexus==0.48.2",
    "tierkreis",
    "tkr-quantinuum-worker"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"



[tool.uv.sources]
tkr-quantinuum-worker = { workspace = true }

[project.scripts]
tkr-quantinuum-worker = "tkr_quantinuum_worker_impl.main:main"
