[project]
name = "tkr-nexus-worker"
version = "0.2.1"
description = "The api for the Tierkreis nexus worker."
requires-python = ">=3.12"
authors = [ {name = "Quantinuum Tierkreis Team"} ]
dependencies = [
    "tierkreis",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel.force-include]
"api.py" = "nexus_worker.py"
