[project]
name = "tkr-my-example-worker-impl"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.11.7",
    "pytket>=2.9.3",
    "tierkreis",
    "ruff",
    "sympy",
    "pytket-qiskit",
    "tkr-my-example-worker",
]

[tool.uv.sources]
tierkreis = { workspace = true }
tkr-my-example-worker = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"



[project.scripts]
tkr-my-example-worker = "tkr_my_example_worker_impl.main:main"
