name: Release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-24.04
    environment: pypi
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up deps
        uses: ./.github/actions/setup_deps
        with:
          include_node: "yes"

      - name: Build frontend
        run: just prod

      - name: Build Python package
        run: |
          uv build tierkreis
          uv build tierkreis_visualization
          uv build tierkreis_workers/aer_worker
          uv build tierkreis_workers/aer_worker/api
          uv build tierkreis_workers/ibmq_worker
          uv build tierkreis_workers/ibmq_worker/api
          uv build tierkreis_workers/nexus_worker
          uv build tierkreis_workers/nexus_worker/api
          uv build tierkreis_workers/pytket_worker
          uv build tierkreis_workers/pytket_worker/api
          uv build tierkreis_workers/quantinuum_worker
          uv build tierkreis_workers/quantinuum_worker/api
          uv build tierkreis_workers/qulacs_worker
          uv build tierkreis_workers/qulacs_worker/api

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          skip-existing: true
